[client]
showErrorDetails = "none"
toolbarMode = "viewer"
showErrorLinks = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 2

[browser]
gatherUsageStats = false

[logger]
level = "warning"

[theme]
base = "light"
primaryColor = "#FF3621"
backgroundColor = "#F9F7F4"
secondaryBackgroundColor = "#EEEDE9"
textColor = "#0B2026"
font = "sans serif"
